---
title: "PyQGIS Workshop - v2021.2 - Part 0"
author: "Mikael Vaaltola - Gispo Ltd."
date: "2021-02-21"
output: html_document
---

# Before starting

This document describes a few steps you should take first.

## Prerequisites

Before starting work on QGIS plugins, it's beneficial to have a few things installed.

### Required

You should install all of these on your own computer before starting QGIS plugin development.

- QGIS 3.x, preferably the latest stable version.
- Python 3.x. QGIS already ships with Python, but if you are on Windows it's good to have a system-wide install of Python as well.
- An IDE/text editor to work with Python code. **Don't** use notepad, notepad++, or gedit!
    - If unsure, Visual Studio Code is a free and decent choice to get started. Make sure to install the Python plugin for it.
    - PyCharm is another good choice.

#### Note to Windows users

After installing QGIS and Python, make sure to include the QGIS Python libraries in your PythonPath.

1. Open OSGeo4W Shell from the start menu, this should come with your QGIS installation.
2. Type in `py3_env` and hit enter.
3. Type in `python3` and hit enter.
4. Type `import qgis` and hit enter.

If this results in an error, your Python environment needs to be configured.

- Read [this guide](https://www.architectryan.com/2018/08/31/how-to-change-environment-variables-on-windows-10/) first if you need help on setting up environment variables in Windows.
- Check your QGIS installation directory, most likely something like `C:\Program Files\QGIS 3.16` but could vary based on your QGIS version and OS.
- Go to edit your PYTHONPATH environment variable.
- Add the following to the **end** of the current PYTHONPATH value, making sure to match your QGIS installation path:
`;C:\Program Files\QGIS 3.16\apps\qgis\python`
- Reboot for good measure,

Follow steps 1-4 above again and verify there are no error messages after running the `import qgis` command.

#### Note to MacOS users

Similarly to the Windows environment, the QGIS Python libraries need to be in your PythonPath.

1. Open Terminal.
2. Type in `python3` and hit enter.
3. Type `import qgis` and hit enter.

If this results in an error, your Python environment needs to be configured. QGIS for MacOS contains its own python interpreter, which you may use to ensure that all the correct python libraries are present.

- *If you use pyenv*: you may use [this guide](https://gist.github.com/mkpaa/e8a5b349d02c6677e38d9ac505019312) to set pyenv to use the python interpreter contained in QGIS. Check that after activating the pyenv, `python --version` returns `Python 3.8.7`. If you get version 2, you have to add the python->python3 symlink inside QGIS: `ln -s /Applications/QGIS.app/Contents/MacOS/bin/python /Applications/QGIS.app/Contents/MacOS/bin/python3`. Recreate the pyenv after that. (Using pyenv is necessary if you are using an M1 processor Mac, as the system python binaries are for the ARM architecture and cannot import QGis libraries that are compiled for x86 processors. The QGIS internal python, or running some other x86 python emulated, is needed.)
- Alternatively, set up your python to find qgis libraries by adding `export PYTHONPATH=/Applications/QGIS.app/Contents/Resources/python`. More instructions for running qgis libraries in external python are found in [PyQGIS Introduction](https://docs.qgis.org/3.16/en/docs/pyqgis_developer_cookbook/intro.html#running-custom-applications).

Follow steps 1-3 above again and verify there are no error messages after running the `import qgis` command.

### Highly recommended

These are highly useful tools to have.

- Admin/sudo permissions so you can freely install software.
- Qt Designer and Qt Linguist for UI design and translation.
- Git for source code version control and jumping through the different tags within this repo.
    - A GitHub or GitLab account, or an account to some other similar platform that ideally supports running tests and other automated processes.
- A debugger. PyCharm has a really nice debugger, and Vs Code also supports Python debugging. It's useful if you already know at least some basics of how to set up and use the debugger in whichever IDE/editor you pick.

### Useful

These are often useful tools to have, but not strictly necessary.

- Linux, or more specifically, dual-boot. Linux makes development less complicated, and having Windows available makes debugging potential OS-specific issues easier.
- Docker to simplify running unit tests, hosting databases, and trying different versions of QGIS.
- PostgreSQL and PostGIS, used by many QGIS plugins.
- A Transifex account, if doing translations in Transifex.


## [Next part](https://htmlpreview.github.io/?https://github.com/GispoCoding/pyqgis_workshop/blob/master/docs/pyqgis-1_python.html)
